version: '3.7' ## Latest version works with Docker Engine release 18.06.0+

services:
  ## Start - Product service definition
  product:
    build: store-services/product-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongodb
      - rabbitmq
  ## End - Product service definition

  ## Start - Recommendation service definition
  recommendation:
    build: store-services/recommendation-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongodb
      - rabbitmq
  ## End - Recommendation service definition

  ## Start - Review service definition
  review:
    build: store-services/review-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql
      - rabbitmq
    restart: on-failure
  ## End - Review service definition

  ## Start - Store service definition
  store:
    build: store-services/store-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - rabbitmq
  ## End - Store service definition

  ## Start - mongodb database definition
  ### $ mongo
  mongodb:
    image: mongo:4.2.5-bionic
    ports:
      - "27017-27019:27017-27019"
    healthcheck:
      test: "mongo --eval 'db.stats().ok'"
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: on-failure
  ## End - mongodb database definition

  ## Start - MySql database definition
  ### $ mysql -uroot -h127.0.0.1 -p
  mysql:
    image: mysql:8.0.19
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=review-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
      - MYSQL_ROOT_HOST=%
    healthcheck:
      test: "/usr/bin/mysql --user=user --password=pwd --execute \"SHOW DATABASES;\""
      interval: 10s
      timeout: 5s
      retries: 10
    restart: on-failure
  ## End - MySql database definition

  ## Start - RabbitMQ Messaging service
  rabbitmq:
    image: rabbitmq:3.8.3-management
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: on-failure
  ## End - RabbitMQ Messaging service
