spring:
  application:
    name: recommendation-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: recommendation-db
      auto-index-creation: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      defaultBinder: rabbit
      default:
        contentType: application/json
      bindings:
        input:
          destination: recommendations
          group: recommendationsGroup
          consumer:
            maxAttempts: 3
            backOffInitialInterval: 500
            backOffMaxInterval: 1000
            backOffMultiplier: 2.0
      rabbit:
        bindings:
          input:
            consumer:
              autoBindDlq: true
              republishToDlq: true
      kafka:
        bindings:
          input:
            consumer:
              enableDlq: true
        binder:
          brokers: 127.0.0.1
          defaultBrokerPort: 9092

server:
  port: 9082

logging:
  level:
    web: DEBUG
    root: INFO
    com.siriusxi.ms.store: DEBUG
    org:
      springframework.data.mongodb.core.MongoTemplate: DEBUG
      mongodb: debug

management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always

# This is a docker specific profile properties
# Also profiles could be separated in its owen file
# with file name format of "application-docker.yaml"
---
spring:
  profiles: docker
  jmx:
    enabled: false
  data:
    mongodb:
      host: mongodb
  rabbitmq:
    host: rabbitmq
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka

server:
  port: 8080
