spring:
  application:
    name: recommendation-service

server:
  port: 9082

logging:
  level:
    web: DEBUG
    root: INFO
    com.siriusxi.ms:.store: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
