spring:
  application:
    name: recommendation-service

server:
  port: 9082

logging:
  level:
    web: DEBUG
    root: INFO
    com.siriusxi.ms:.store: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

# This is a docker specific profile properties
# Also profiles could be separated in its owen file
# with file name format of "application-docker.yaml"
---
spring:
  profiles: docker

server:
  port: 8080
