spring:
  application:
    name: product-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-db

server:
  port: 9081

logging:
  level:
    web: DEBUG
    root: INFO
    com.siriusxi.ms.store: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

# This is a docker specific profile properties
# Also profiles could be separated in its owen file
# with file name format of "application-docker.yaml"
---
spring:
  profiles: docker
  jmx:
    enabled: false
  data:
    mongodb:
      host: mongodb

server:
  port: 8080