spring:
  application:
    name: review-service

  jpa:
    show-sql: true
    open-in-view: false
    database: MYSQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      # Strongly recommend to set this property to "none" or with flyway  to "validate" in a
      # production environment!
      ddl-auto: none
  datasource:
    ## You often do not need to specify the driver-class-name,
    ## since Spring Boot can deduce it for most databases from the url.
    #driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    url: "jdbc:mysql://localhost/review-db?useSSL=false&serverTimezone=UTC"
    username: user
    password: pwd
    hikari:
      initializationFailTimeout: 60000
      connection-test-query: SELECT 1

  flyway:
    #Enable or disable flyway migrations
    enabled: true
    url: "jdbc:mysql://localhost/mysql?useSSL=false&serverTimezone=UTC"
    schemas: review-db
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

server:
  port: 9083

logging:
  level:
    web: DEBUG
    root: INFO
    com.siriusxi.ms.store: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE

management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

# This is a docker specific profile properties
# Also profiles could be separated in its owen file
# with file name format of "application-docker.yaml"
---
spring:
  profiles: docker
  jmx:
    enabled: false
  datasource:
    url: "jdbc:mysql://mysql/review-db"
  jpa:
    hibernate:
      ddl-auto: update
  # FIXME to enable docker compose to run with flyway
  flyway:
    enabled: false
    url: "jdbc:mysql://mysql/mysql?useSSL=false&serverTimezone=UTC"

server:
  port: 8080