spring:
  application:
    name: review-service

  jpa:
    hibernate:
      # Strongly recommend to set this property to "none" in a production environment!
      ddl-auto: update
  datasource:
    url: "jdbc:mysql://localhost/review-db"
    username: user
    password: pwd
    hikari:
      initializationFailTimeout: 60000

server:
  port: 9083

logging:
  level:
    web: DEBUG
    root: INFO
    com.siriusxi.ms.store: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

# This is a docker specific profile properties
# Also profiles could be separated in its owen file
# with file name format of "application-docker.yaml"
---
spring:
  profiles: docker
  jmx:
    enabled: false
  datasource:
    url: "jdbc:mysql://mysql/review-db"

server:
  port: 8080